name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [created, released, deleted]
  workflow_dispatch: 

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check code
        run: cargo check

      - name: Run tests
        run: cargo test

      # - name: MSRV
      #   run: |
      #     rustup component add rustfmt
      #     cargo install cargo-msrv
      #     cargo msrv --check

      # - name: Install clippy
      #   run: rustup component and clippy

      # - name: Run clippy
      #   uses: actions-rs/clippy-check@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     args: --all-features

  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    needs: check
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] 
        rust: [stable]
        arch: [x86_64, aarch64]
        exclude:
          - os: windows-latest
            arch: aarch64
          # - os: macos-latest
          #   arch: aarch64
          # - os: ubuntu-latest
          #   arch: aarch64
          - os: windows-latest
            arch: x86_64
          # - os: macos-latest
          #   arch: x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      
      - name: post-rust-install on Linux/x86_64
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'x86_64'
        run: |
          cargo install cargo-msrv
          cargo install cargo-script
          cargo install cargo-deb
          cargo install cargo-rpm
          rustup target add x86_64-unknown-linux-gnu

      - name: post-rust-install on Linux/aarch64
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'aarch64'
        run: |
          cargo install cargo-msrv
          cargo install cargo-script
          cargo install cargo-deb
          cargo install cargo-rpm
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          rustup target add aarch64-unknown-linux-gnu

      - name: post-rust-install on Windows/x86_64
        if: matrix.os == 'windows-latest' && matrix.arch == 'x86_64'
        run: |
          cargo install cargo-msrv
          cargo install cargo-script
          cargo install cargo-wix 
          rustup target add x86_64-pc-windows-msvc

      - name: post-rust-install on Windows/aarch64
        if: matrix.os == 'windows-latest' && matrix.arch == 'aarch64'
        run: |
          cargo install cargo-msrv
          cargo install cargo-script
          cargo install cargo-wix 
          rustup target add aarch64-pc-windows-msvc
          Invoke-WebRequest -Uri "https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-win32.exe" -OutFile "gcc-arm-none-eabi.exe"
          Start-Process -FilePath "gcc-arm-none-eabi.exe" -ArgumentList "/S" -Wait
          echo "C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: post-rust-install on macOS/x86_64
        if: matrix.os == 'macos-latest' && matrix.arch == 'x86_64'
        run: |
          cargo install cargo-msrv
          cargo install cargo-script
          cargo install cargo-bundle
          rustup target add x86_64-apple-darwin

      - name: post-rust-install on macOS/aarch64
        if: matrix.os == 'macos-latest' && matrix.arch == 'aarch64'
        run: |
          cargo install cargo-msrv
          cargo install cargo-script
          cargo install cargo-bundle
          brew install FiloSottile/musl-cross/musl-cross
          rustup target add aarch64-unknown-linux-musl
          rustup target add aarch64-apple-darwin

      - name: tag to version on Linux/macOS
        if: matrix.os != 'windows-latest' && github.event_name == 'release' #&& github.event.action == 'published'
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          cargo script ./scripts/update_version.rs $VERSION

      - name: tag to version on Windows
        if: matrix.os == 'windows-latest' && github.event_name == 'release' #&& github.event.action == 'published'
        run: |
          echo "VERSION=$env:GITHUB_REF" >> $env:GITHUB_ENV
          cargo script ./scripts/update_version.rs $env:VERSION

      - name: Build on Linux/x86_64
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'x86_64'
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Build on Linux/aarch64
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'aarch64'
        run: cargo build --release --target aarch64-unknown-linux-gnu

      - name: Build on macOS/x86_64
        if: matrix.os == 'macos-latest' && matrix.arch == 'x86_64'
        run: |
          cargo build --release -vv --target x86_64-apple-darwin

      - name: Build on macOS/aarch64
        if: matrix.os == 'macos-latest' && matrix.arch == 'aarch64'
        run: cargo build --release -vv --target aarch64-unknown-linux-musl

      - name: Build on Windows/x86_64
        if: matrix.os == 'windows-latest' && matrix.arch == 'x86_64'
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Build on Windows/aarch64
        if: matrix.os == 'windows-latest' && matrix.arch == 'aarch64'
        run: cargo build --release --target aarch64-pc-windows-msvc

      - name: Install tree on macOS
        if: matrix.os == 'macos-latest'
        run: brew install tree

      - name: Install tree on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Install tree on Windows
        if: matrix.os == 'windows-latest'
        run: choco install tree

      - name: List directory structure
        run: tree

      - name: Run tests on Linux/x86_64
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'x86_64'
        run: |
          cargo test --release --target x86_64-unknown-linux-gnu

# Do I need QEMU for aarch64 tests?

      - name: Run tests on macOS/x86_64
        if: matrix.os == 'macos-latest' && matrix.arch == 'x86_64'
        run: |
          cargo test --release --target x86_64-apple-darwin

# Do I need QEMU for aarch64 tests?

      - name: Run tests on Windows/x86_64
        if: matrix.os == 'windows-latest' && matrix.arch == 'x86_64'
        run: cargo test --release --target x86_64-pc-windows-msvc


# here we build the packages for the os-es ...

# then we upload the artifacts

# then we deploy  the rpm/deb/msi packages
# and what about pip & conda
# and what about uploading to crates.io ?

     

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.event_name == 'release' && github.event.action == 'published'
  #   steps:
  #     - uses: actions/checkout@v2

